
name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: csunibo/config/.github/workflows/statik.yml@new_statik
    with:
      regex_include: "\\.(pdf|link|txt|apkg)$"
